apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: superset
spec:
  rules:
  - host: superset.dev.meson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: superset
          servicePort: 9000
