apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-release-ecr
spec:
  description: |
    golang-release-ecr
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.

  - name: dockerRepoUrl
    type: string
  - name: env
    type: string
  - name: appName
    type: string

  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.

  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)

  - name: version-builder
    runAfter: [ "fetch-repo" ]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      results:
      - name: version
        description: version for rest of the process
      steps:
      - image: docker.io/python:3.9-buster
        script: |
          #!/usr/bin/env bash
          set -ex

          cd $(workspaces.source.path)
          git config user.name "meson-bot"
          git config user.email "meson-bot@meson.ai"

          pip install semver

          pysemver bump patch $(cat VERSION) > VERSION

          git checkout -b master
          git add VERSION
          git commit -m "Release version $(cat VERSION)"
          cat VERSION | tr -d '\n' | tee $(results.version.path)

  - name: echo
    runAfter:
    - version-builder
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: args
      value: "$(params.dockerRepoUrl)/$(params.env)/$(params.appName):$(tasks.version-builder.results.version)"
    taskSpec:
      workspaces:
      - name: source
      params:
      - name: args
        type: string
      steps:
      - image: zshusers/zsh:4.3.15
        script: |
          #!/usr/bin/env zsh
          #cat $(workspaces.source.path)/README.md
          echo "$(params.args)"

  - name: go-build
    runAfter:
    - version-builder

    # conditions:
    #   - conditionRef: "go-test"
    #     resources:
    #       - name: source-repo
    #         resource: source-repo

    workspaces:
    - name: source
      workspace: shared-data
    taskRef:
      name: golang-make
    params:
    - name: args
      value: make

  - name: docker-build-publish
    taskRef:
      name: kaniko
    runAfter: [ "go-build" ]
    workspaces:
    - name: source
      workspace: shared-data
    params:
    # - name: CONTEXT
    #   value: ./
    # - name: DOCKERFILE
    #   value: Dockerfile
    - name: IMAGE
      value: "$(params.dockerRepoUrl)/$(params.env)/$(params.appName):$(tasks.version-builder.results.version)"

  - name: helm-push
    runAfter:
    - docker-build-publish
    workspaces:
    - name: source
      workspace: shared-data
    taskRef:
      name: helm-push
    params:
    - name: chartName
      value: $(params.appName)
    - name: version
      value: $(tasks.version-builder.results.version)


  - name: push-tag
    runAfter: [ "helm-push" ]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      steps:
      - image: docker.io/python:3.9-buster
        script: |
          #!/usr/bin/env bash
          set -ex

          cd $(workspaces.source.path)
          git config user.name "meson-bot"
          git config user.email "meson-bot@meson.ai"
          ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts
          ls $HOME/.ssh/
          echo "Pushing detached tag of new version"

          git tag  -a "v$(cat VERSION)" -m "Release version $(cat VERSION) tag"
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $HOME/.ssh/id_git-ssh " git push origin master --follow-tags
          echo "done"

---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: go-test
  namespace: getting-started
spec:
  resources:
  - name: source-repo
    type: git
  check:
    image: golang
    command: [ "go" ]
    workingDir: "$(resources.source-repo.path)"
    args: [ 'test', "./..." ]
