apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: imageUrl
      description: docker image url relative to ECR
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: getting-started-pipeline-run-$(uid)
        namespace: tekton-pipelines
      spec:
        serviceAccountName: meson-bot
        pipelineRef:
          name: golang-release-ecr
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        params:
        - name: repo-url
          value: $(tt.params.gitrepositoryurl) 
        - name: branch-name
          value: $(tt.params.gitrevision)
        - name: imageUrl
          value: 004245605591.dkr.ecr.ap-south-1.amazonaws.com/$(tt.params.imageUrl)
        - name: imageTag
          value: "1.1"

      # - name: event-to-sink
      #   resourceSpec:
      #     type: cloudEvent
      #     params:
      #       - name: targetURI
      #         value: http://event-display.getting-started.svc.cluster.local
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: master
      # value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: "git@github.com:$(body.repository.full_name)"
    - name: imageUrl
      value: "prod/hello-go"
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: getting-started-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - ref: getting-started-pipelinebinding
      template:
        ref: getting-started-triggertemplate

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: el-getting-started-listener
spec:
  rules:
  - host: tkn-go.65.0.188.135.nip.io
    http:
      paths:
      - backend:
          serviceName: el-getting-started-listener
          servicePort: 8080
