apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  size: 10Gi
  storageClassName: standard

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-artifact-pvc
#   namespace: tekton-pipelines
#   labels:
#     app.kubernetes.io/instance: default
#     app.kubernetes.io/part-of: tekton-pipelines
# data:
#   default-cloud-events-sink: https://my-sink-url
  
---
# https://github.com/tektoncd/pipeline/blob/master/docs/install.md#configuring-self-signed-cert-for-private-registry
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-registry-cert
#   namespace: tekton-pipelines
#   labels:
#     app.kubernetes.io/instance: default
#     app.kubernetes.io/part-of: tekton-pipelines
# data:
#   cert: asdsads
  
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  taskRef:
    name: echo-hello-world
  